# segment pour accéder à Cockpit (9090)
admin_cidr: "10.10.10.0/24"

# Liste d'IP/CIDR autorisées en SSH (partout si par défaut)
ssh_allow_cidrs:
  - "10.10.10.0/24"
  - "X.X.X.X/24"
  - "X.X.X.X/32"

# Activer le TOTP (PAM) pour SSH si besoin
enable_totp: false

# Fail2ban sshd
f2b_sshd_maxretry: 3
f2b_sshd_findtime: 600    # 10 min
f2b_sshd_bantime: 3600    # 1h

# Polkit libvirt : mapping groupes (aucune exception utilisateur)
polkit_admin_groups:
  - ops-admin
polkit_maint_groups:
  - ops-maint
polkit_read_groups:
  - ops-read

ops_users:
  - name: bob
    groups: [ops-maint]
    ssh_pubkeys:
      - "XXX...<nom>@projet"


# Fixer l’IP d’écoute de cockpit.socket si nécessaire (vide = comportement par défaut)
cockpit_bind_ip: ""
