# acces cockpit (9090)
admin_cidr: "10.10.10.0/24"

# ip/cidr autorisees en ssh
ssh_allow_cidrs:
  - "10.10.10.0/24"
  - "192.168.56.0/24"


# active TOTP (PAM) pour SSH, false = cl√© seule
enable_totp: false

# fail2ban sshd
f2b_sshd_maxretry: 3
f2b_sshd_findtime: 600   
f2b_sshd_bantime: 3600    
